blank_issues_enabled: false
contact_links:
  - name: 💬 Discussion
    url: https://github.com/sanhee/tab-nexus/discussions
    about: 일반적인 질문이나 아이디어 논의
  - name: 📚 Documentation
    url: https://github.com/sanhee/tab-nexus/wiki
    about: 프로젝트 문서 및 가이드